server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication_db
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: tuldse184668@fpt.edu.vn
    password: fryzapjrxznpmkyc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

jwt:
  secret: V7Pz0c5ZmTz4IVBdBrgiapaNOSKpRDWtT8AsXm+C1mE=
  access-token-expiration: 900000 # 15 minutes (ms)
  refresh-token-expiration: 604800000 # 7 days (ms)